import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Text from "../components/text/text";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="en">
		<head>
			<link rel="preconnect" href="https://fonts.googleapis.com"/>
			<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
			<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"/>	
		</head>
		<body>
			<NavBar/>
			{children}
		</body>
		</html>
	);
}

function NavBar(){
	return <nav className="flex gap-5 p-4 border-b border-neutral-200 items-center">
		<Link href='/'>
			<Text size='h5'>Cakes and bakes</Text>
		</Link>
		<Link href='/order'>Order</Link>
		<Link href='/cart'>Cart</Link>
		<Link href='/checkout' className="ml-auto">Checkout</Link>
	</nav>
}
